#!/bin/bash
venv/bin/python3 -m yt_dlp --restrict-filenames --print-to-file after_move:filepath "../.playlist" -o "%(description.0:100)s" --batch-file ".to_download" --paths ".vids/"; > ".to_download"
